# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /blog/:year/:month/:day/:title/


# Setup
title:               Brandon Walsh
tagline:
description:         "Head of Graduate Programs at the Scholars' Lab in the UVA Library"
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Brandon Walsh
  url:               https://twitter.com/mdo
  email:             walsh@virginia.edu

# Custom vars
version:             1.0.0


plugins_dir: ./_plugins
plugins: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
category_dir: 'categories'
